// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package flowaisdkgo

// Generated from OpenAPI doc version 0.1.0 and generator version 2.616.1

import (
	"fmt"
	"github.com/flowaicom/flowai-sdk-go/internal/config"
	"github.com/flowaicom/flowai-sdk-go/internal/hooks"
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"github.com/flowaicom/flowai-sdk-go/retry"
	"net/http"
	"time"
)

// ServerList contains the list of servers available to the SDK
var ServerList = []string{
	// Local development server
	"http://localhost:8000",
}

// HTTPClient provides an interface for supplying the SDK with a custom HTTP client
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// String provides a helper function to return a pointer to a string
func String(s string) *string { return &s }

// Bool provides a helper function to return a pointer to a bool
func Bool(b bool) *bool { return &b }

// Int provides a helper function to return a pointer to an int
func Int(i int) *int { return &i }

// Int64 provides a helper function to return a pointer to an int64
func Int64(i int64) *int64 { return &i }

// Float32 provides a helper function to return a pointer to a float32
func Float32(f float32) *float32 { return &f }

// Float64 provides a helper function to return a pointer to a float64
func Float64(f float64) *float64 { return &f }

// Pointer provides a helper function to return a pointer to a type
func Pointer[T any](v T) *T { return &v }

// FlowAI - server: FastAPI backend for Flow Expert
type FlowAI struct {
	SDKVersion      string
	Health          *Health
	Webhooks        *Webhooks
	Users           *Users
	TestCases       *TestCases
	Validations     *Validations
	Batches         *Batches
	APIKeys         *APIKeys
	Auth            *Auth
	Authentication  *Authentication
	Datasets        *Datasets
	Jobs            *Jobs
	Projects        *Projects
	ValidationTasks *ValidationTasks
	ValidatorTasks  *ValidatorTasks
	Stages          *Stages
	Integrations    *Integrations
	Root            *Root

	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

type SDKOption func(*FlowAI)

// WithServerURL allows the overriding of the default server URL
func WithServerURL(serverURL string) SDKOption {
	return func(sdk *FlowAI) {
		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithTemplatedServerURL allows the overriding of the default server URL with a templated URL populated with the provided parameters
func WithTemplatedServerURL(serverURL string, params map[string]string) SDKOption {
	return func(sdk *FlowAI) {
		if params != nil {
			serverURL = utils.ReplaceParameters(serverURL, params)
		}

		sdk.sdkConfiguration.ServerURL = serverURL
	}
}

// WithServerIndex allows the overriding of the default server by index
func WithServerIndex(serverIndex int) SDKOption {
	return func(sdk *FlowAI) {
		if serverIndex < 0 || serverIndex >= len(ServerList) {
			panic(fmt.Errorf("server index %d out of range", serverIndex))
		}

		sdk.sdkConfiguration.ServerIndex = serverIndex
	}
}

// WithClient allows the overriding of the default HTTP client used by the SDK
func WithClient(client HTTPClient) SDKOption {
	return func(sdk *FlowAI) {
		sdk.sdkConfiguration.Client = client
	}
}

func WithRetryConfig(retryConfig retry.Config) SDKOption {
	return func(sdk *FlowAI) {
		sdk.sdkConfiguration.RetryConfig = &retryConfig
	}
}

// WithTimeout Optional request timeout applied to each operation
func WithTimeout(timeout time.Duration) SDKOption {
	return func(sdk *FlowAI) {
		sdk.sdkConfiguration.Timeout = &timeout
	}
}

// New creates a new instance of the SDK with the provided options
func New(opts ...SDKOption) *FlowAI {
	sdk := &FlowAI{
		SDKVersion: "0.0.6",
		sdkConfiguration: config.SDKConfiguration{
			UserAgent:  "speakeasy-sdk/go 0.0.6 2.616.1 0.1.0 github.com/flowaicom/flowai-sdk-go",
			ServerList: ServerList,
		},
		hooks: hooks.New(),
	}
	for _, opt := range opts {
		opt(sdk)
	}

	// Use WithClient to override the default client if you would like to customize the timeout
	if sdk.sdkConfiguration.Client == nil {
		sdk.sdkConfiguration.Client = &http.Client{Timeout: 60 * time.Second}
	}

	sdk.sdkConfiguration = sdk.hooks.SDKInit(sdk.sdkConfiguration)

	sdk.Health = newHealth(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Webhooks = newWebhooks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Users = newUsers(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.TestCases = newTestCases(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Validations = newValidations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Batches = newBatches(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.APIKeys = newAPIKeys(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Auth = newAuth(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Authentication = newAuthentication(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Datasets = newDatasets(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Jobs = newJobs(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Projects = newProjects(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.ValidationTasks = newValidationTasks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.ValidatorTasks = newValidatorTasks(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Stages = newStages(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Integrations = newIntegrations(sdk, sdk.sdkConfiguration, sdk.hooks)
	sdk.Root = newRoot(sdk, sdk.sdkConfiguration, sdk.hooks)

	return sdk
}
