// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type AddProjectValidatorProjectsProjectIDValidatorsPostRequest struct {
	ProjectID              string                            `pathParam:"style=simple,explode=false,name=project_id"`
	ProjectValidatorCreate components.ProjectValidatorCreate `request:"mediaType=application/json"`
}

func (o *AddProjectValidatorProjectsProjectIDValidatorsPostRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *AddProjectValidatorProjectsProjectIDValidatorsPostRequest) GetProjectValidatorCreate() components.ProjectValidatorCreate {
	if o == nil {
		return components.ProjectValidatorCreate{}
	}
	return o.ProjectValidatorCreate
}

type AddProjectValidatorProjectsProjectIDValidatorsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ProjectValidatorResponse *components.ProjectValidatorResponse
}

func (o *AddProjectValidatorProjectsProjectIDValidatorsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AddProjectValidatorProjectsProjectIDValidatorsPostResponse) GetProjectValidatorResponse() *components.ProjectValidatorResponse {
	if o == nil {
		return nil
	}
	return o.ProjectValidatorResponse
}
