// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type CheckValidationTaskStatusValidationTasksValidationTaskIDGetRequest struct {
	ValidationTaskID string `pathParam:"style=simple,explode=false,name=validation_task_id"`
}

func (o *CheckValidationTaskStatusValidationTasksValidationTaskIDGetRequest) GetValidationTaskID() string {
	if o == nil {
		return ""
	}
	return o.ValidationTaskID
}

type CheckValidationTaskStatusValidationTasksValidationTaskIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ValidationTaskRead *components.ValidationTaskRead
}

func (o *CheckValidationTaskStatusValidationTasksValidationTaskIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CheckValidationTaskStatusValidationTasksValidationTaskIDGetResponse) GetValidationTaskRead() *components.ValidationTaskRead {
	if o == nil {
		return nil
	}
	return o.ValidationTaskRead
}
