// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type CompleteValidatorSignupAuthValidatorsCompleteSignupPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseCompleteValidatorSignupAuthValidatorsCompleteSignupPost any
}

func (o *CompleteValidatorSignupAuthValidatorsCompleteSignupPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CompleteValidatorSignupAuthValidatorsCompleteSignupPostResponse) GetResponseCompleteValidatorSignupAuthValidatorsCompleteSignupPost() any {
	if o == nil {
		return nil
	}
	return o.ResponseCompleteValidatorSignupAuthValidatorsCompleteSignupPost
}
