// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type CreateValidationTaskForBatchEndpointBatchesBatchIDValidationTasksPostRequest struct {
	BatchID string `pathParam:"style=simple,explode=false,name=batch_id"`
}

func (o *CreateValidationTaskForBatchEndpointBatchesBatchIDValidationTasksPostRequest) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

type CreateValidationTaskForBatchEndpointBatchesBatchIDValidationTasksPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	CreateValidationTaskResponse *components.CreateValidationTaskResponse
}

func (o *CreateValidationTaskForBatchEndpointBatchesBatchIDValidationTasksPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateValidationTaskForBatchEndpointBatchesBatchIDValidationTasksPostResponse) GetCreateValidationTaskResponse() *components.CreateValidationTaskResponse {
	if o == nil {
		return nil
	}
	return o.CreateValidationTaskResponse
}
