// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type CreateStagesForProjectStagesPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseCreateStagesForProjectStagesPost []components.StageDetailsResponse
}

func (o *CreateStagesForProjectStagesPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateStagesForProjectStagesPostResponse) GetResponseCreateStagesForProjectStagesPost() []components.StageDetailsResponse {
	if o == nil {
		return nil
	}
	return o.ResponseCreateStagesForProjectStagesPost
}
