// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type CreateJobForProjectProjectsProjectIDJobsPostRequest struct {
	ProjectID string               `pathParam:"style=simple,explode=false,name=project_id"`
	JobCreate components.JobCreate `request:"mediaType=application/json"`
}

func (o *CreateJobForProjectProjectsProjectIDJobsPostRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreateJobForProjectProjectsProjectIDJobsPostRequest) GetJobCreate() components.JobCreate {
	if o == nil {
		return components.JobCreate{}
	}
	return o.JobCreate
}

type CreateJobForProjectProjectsProjectIDJobsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	JobResponse *components.JobResponse
}

func (o *CreateJobForProjectProjectsProjectIDJobsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateJobForProjectProjectsProjectIDJobsPostResponse) GetJobResponse() *components.JobResponse {
	if o == nil {
		return nil
	}
	return o.JobResponse
}
