// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type CreateAPIKeyForUserAPIKeysPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	APIKeyCreateResponse *components.APIKeyCreateResponse
}

func (o *CreateAPIKeyForUserAPIKeysPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAPIKeyForUserAPIKeysPostResponse) GetAPIKeyCreateResponse() *components.APIKeyCreateResponse {
	if o == nil {
		return nil
	}
	return o.APIKeyCreateResponse
}
