// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type CreateProjectProjectsPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ProjectResponse *components.ProjectResponse
}

func (o *CreateProjectProjectsPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateProjectProjectsPostResponse) GetProjectResponse() *components.ProjectResponse {
	if o == nil {
		return nil
	}
	return o.ProjectResponse
}
