// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type DeleteValidationValidationsValidationIDDeleteRequest struct {
	ValidationID       string `pathParam:"style=simple,explode=false,name=validation_id"`
	CurrentUserPayload any    `queryParam:"style=form,explode=true,name=current_user_payload"`
}

func (o *DeleteValidationValidationsValidationIDDeleteRequest) GetValidationID() string {
	if o == nil {
		return ""
	}
	return o.ValidationID
}

func (o *DeleteValidationValidationsValidationIDDeleteRequest) GetCurrentUserPayload() any {
	if o == nil {
		return nil
	}
	return o.CurrentUserPayload
}

type DeleteValidationValidationsValidationIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteValidationValidationsValidationIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
