// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type DeleteProjectProjectsProjectIDDeleteRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

func (o *DeleteProjectProjectsProjectIDDeleteRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

type DeleteProjectProjectsProjectIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteProjectProjectsProjectIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
