// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type DeleteTestCaseTestCasesTestCaseIDDeleteRequest struct {
	TestCaseID string                `pathParam:"style=simple,explode=false,name=test_case_id"`
	JWTPayload components.JWTPayload `request:"mediaType=application/json"`
}

func (o *DeleteTestCaseTestCasesTestCaseIDDeleteRequest) GetTestCaseID() string {
	if o == nil {
		return ""
	}
	return o.TestCaseID
}

func (o *DeleteTestCaseTestCasesTestCaseIDDeleteRequest) GetJWTPayload() components.JWTPayload {
	if o == nil {
		return components.JWTPayload{}
	}
	return o.JWTPayload
}

type DeleteTestCaseTestCasesTestCaseIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteTestCaseTestCasesTestCaseIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
