// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type DeleteBatchByIDBatchesBatchIDDeleteRequest struct {
	BatchID string `pathParam:"style=simple,explode=false,name=batch_id"`
}

func (o *DeleteBatchByIDBatchesBatchIDDeleteRequest) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

type DeleteBatchByIDBatchesBatchIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteBatchByIDBatchesBatchIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
