// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type DeleteDatasetDatasetsDatasetIDDeleteRequest struct {
	DatasetID string `pathParam:"style=simple,explode=false,name=dataset_id"`
}

func (o *DeleteDatasetDatasetsDatasetIDDeleteRequest) GetDatasetID() string {
	if o == nil {
		return ""
	}
	return o.DatasetID
}

type DeleteDatasetDatasetsDatasetIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteDatasetDatasetsDatasetIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
