// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type DeleteStageStagesStageIDDeleteRequest struct {
	StageID int64 `pathParam:"style=simple,explode=false,name=stage_id"`
}

func (o *DeleteStageStagesStageIDDeleteRequest) GetStageID() int64 {
	if o == nil {
		return 0
	}
	return o.StageID
}

type DeleteStageStagesStageIDDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseDeleteStageStagesStageIDDelete map[string]string
}

func (o *DeleteStageStagesStageIDDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteStageStagesStageIDDeleteResponse) GetResponseDeleteStageStagesStageIDDelete() map[string]string {
	if o == nil {
		return nil
	}
	return o.ResponseDeleteStageStagesStageIDDelete
}
