// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GenerateDatasetForJobJobsJobIDGenerateDatasetPostRequest struct {
	JobID                    string                              `pathParam:"style=simple,explode=false,name=job_id"`
	DatasetGenerationRequest components.DatasetGenerationRequest `request:"mediaType=application/json"`
}

func (o *GenerateDatasetForJobJobsJobIDGenerateDatasetPostRequest) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

func (o *GenerateDatasetForJobJobsJobIDGenerateDatasetPostRequest) GetDatasetGenerationRequest() components.DatasetGenerationRequest {
	if o == nil {
		return components.DatasetGenerationRequest{}
	}
	return o.DatasetGenerationRequest
}

type GenerateDatasetForJobJobsJobIDGenerateDatasetPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	JobDatasetGenerationResponse *components.JobDatasetGenerationResponse
}

func (o *GenerateDatasetForJobJobsJobIDGenerateDatasetPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GenerateDatasetForJobJobsJobIDGenerateDatasetPostResponse) GetJobDatasetGenerationResponse() *components.JobDatasetGenerationResponse {
	if o == nil {
		return nil
	}
	return o.JobDatasetGenerationResponse
}
