// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GenerateBatchForJobJobsJobIDGenerateBatchPostRequest struct {
	JobID string `pathParam:"style=simple,explode=false,name=job_id"`
}

func (o *GenerateBatchForJobJobsJobIDGenerateBatchPostRequest) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

type GenerateBatchForJobJobsJobIDGenerateBatchPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	JobBatchGenerationResponse *components.JobBatchGenerationResponse
}

func (o *GenerateBatchForJobJobsJobIDGenerateBatchPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GenerateBatchForJobJobsJobIDGenerateBatchPostResponse) GetJobBatchGenerationResponse() *components.JobBatchGenerationResponse {
	if o == nil {
		return nil
	}
	return o.JobBatchGenerationResponse
}
