// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetBatchByIDBatchesBatchIDGetRequest struct {
	BatchID string `pathParam:"style=simple,explode=false,name=batch_id"`
}

func (o *GetBatchByIDBatchesBatchIDGetRequest) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

type GetBatchByIDBatchesBatchIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	BatchRead *components.BatchRead
}

func (o *GetBatchByIDBatchesBatchIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBatchByIDBatchesBatchIDGetResponse) GetBatchRead() *components.BatchRead {
	if o == nil {
		return nil
	}
	return o.BatchRead
}
