// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetBatchTestCasesBatchesBatchIDTestcasesGetRequest struct {
	BatchID string `pathParam:"style=simple,explode=false,name=batch_id"`
}

func (o *GetBatchTestCasesBatchesBatchIDTestcasesGetRequest) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

type GetBatchTestCasesBatchesBatchIDTestcasesGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseGetBatchTestCasesBatchesBatchIDTestcasesGet []components.TestCaseRead
}

func (o *GetBatchTestCasesBatchesBatchIDTestcasesGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetBatchTestCasesBatchesBatchIDTestcasesGetResponse) GetResponseGetBatchTestCasesBatchesBatchIDTestcasesGet() []components.TestCaseRead {
	if o == nil {
		return nil
	}
	return o.ResponseGetBatchTestCasesBatchesBatchIDTestcasesGet
}
