// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetCurrentUserBasicInfoUsersMeBasicInfoGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (o *GetCurrentUserBasicInfoUsersMeBasicInfoGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetCurrentUserBasicInfoUsersMeBasicInfoGetResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
