// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetDatasetItemsDatasetsDatasetIDItemsGetRequest struct {
	DatasetID string `pathParam:"style=simple,explode=false,name=dataset_id"`
	// Maximum number of dataset items to return.
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of dataset items to skip for pagination.
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (g GetDatasetItemsDatasetsDatasetIDItemsGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetDatasetItemsDatasetsDatasetIDItemsGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetDatasetItemsDatasetsDatasetIDItemsGetRequest) GetDatasetID() string {
	if o == nil {
		return ""
	}
	return o.DatasetID
}

func (o *GetDatasetItemsDatasetsDatasetIDItemsGetRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetDatasetItemsDatasetsDatasetIDItemsGetRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type GetDatasetItemsDatasetsDatasetIDItemsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	DatasetItemListResponse *components.DatasetItemListResponse
}

func (o *GetDatasetItemsDatasetsDatasetIDItemsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDatasetItemsDatasetsDatasetIDItemsGetResponse) GetDatasetItemListResponse() *components.DatasetItemListResponse {
	if o == nil {
		return nil
	}
	return o.DatasetItemListResponse
}
