// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetHealthStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Service is healthy
	ResponseGetHealthStatus map[string]any
}

func (o *GetHealthStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetHealthStatusResponse) GetResponseGetHealthStatus() map[string]any {
	if o == nil {
		return nil
	}
	return o.ResponseGetHealthStatus
}
