// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetJobDetailsJobsJobIDGetRequest struct {
	JobID string `pathParam:"style=simple,explode=false,name=job_id"`
}

func (o *GetJobDetailsJobsJobIDGetRequest) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

type GetJobDetailsJobsJobIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	JobResponse *components.JobResponse
}

func (o *GetJobDetailsJobsJobIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetJobDetailsJobsJobIDGetResponse) GetJobResponse() *components.JobResponse {
	if o == nil {
		return nil
	}
	return o.JobResponse
}
