// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetProjectDatasetProjectsProjectIDDatasetGetRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// Optional specific dataset version ID to retrieve. If omitted, the latest is returned.
	Version *string `queryParam:"style=form,explode=true,name=version"`
}

func (o *GetProjectDatasetProjectsProjectIDDatasetGetRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *GetProjectDatasetProjectsProjectIDDatasetGetRequest) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

type GetProjectDatasetProjectsProjectIDDatasetGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	DatasetRead *components.DatasetRead
}

func (o *GetProjectDatasetProjectsProjectIDDatasetGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetProjectDatasetProjectsProjectIDDatasetGetResponse) GetDatasetRead() *components.DatasetRead {
	if o == nil {
		return nil
	}
	return o.DatasetRead
}
