// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetValidationsForBatchBatchesBatchIDValidationsGetRequest struct {
	BatchID string `pathParam:"style=simple,explode=false,name=batch_id"`
}

func (o *GetValidationsForBatchBatchesBatchIDValidationsGetRequest) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

type GetValidationsForBatchBatchesBatchIDValidationsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseGetValidationsForBatchBatchesBatchIDValidationsGet []components.TestCaseValidationRead
}

func (o *GetValidationsForBatchBatchesBatchIDValidationsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetValidationsForBatchBatchesBatchIDValidationsGetResponse) GetResponseGetValidationsForBatchBatchesBatchIDValidationsGet() []components.TestCaseValidationRead {
	if o == nil {
		return nil
	}
	return o.ResponseGetValidationsForBatchBatchesBatchIDValidationsGet
}
