// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type GetValidationValidationsValidationIDGetRequest struct {
	ValidationID       string `pathParam:"style=simple,explode=false,name=validation_id"`
	CurrentUserPayload any    `queryParam:"style=form,explode=true,name=current_user_payload"`
}

func (o *GetValidationValidationsValidationIDGetRequest) GetValidationID() string {
	if o == nil {
		return ""
	}
	return o.ValidationID
}

func (o *GetValidationValidationsValidationIDGetRequest) GetCurrentUserPayload() any {
	if o == nil {
		return nil
	}
	return o.CurrentUserPayload
}

type GetValidationValidationsValidationIDGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TestCaseValidationRead *components.TestCaseValidationRead
}

func (o *GetValidationValidationsValidationIDGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetValidationValidationsValidationIDGetResponse) GetTestCaseValidationRead() *components.TestCaseValidationRead {
	if o == nil {
		return nil
	}
	return o.TestCaseValidationRead
}
