// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type ListProjectValidatorsProjectsProjectIDValidatorsGetRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
}

func (o *ListProjectValidatorsProjectsProjectIDValidatorsGetRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

type ListProjectValidatorsProjectsProjectIDValidatorsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ProjectValidatorListResponse *components.ProjectValidatorListResponse
}

func (o *ListProjectValidatorsProjectsProjectIDValidatorsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListProjectValidatorsProjectsProjectIDValidatorsGetResponse) GetProjectValidatorListResponse() *components.ProjectValidatorListResponse {
	if o == nil {
		return nil
	}
	return o.ProjectValidatorListResponse
}
