// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type ListJobBatchesForJobJobsJobIDBatchesGetRequest struct {
	JobID  string `pathParam:"style=simple,explode=false,name=job_id"`
	Limit  *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListJobBatchesForJobJobsJobIDBatchesGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListJobBatchesForJobJobsJobIDBatchesGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListJobBatchesForJobJobsJobIDBatchesGetRequest) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

func (o *ListJobBatchesForJobJobsJobIDBatchesGetRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListJobBatchesForJobJobsJobIDBatchesGetRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type ListJobBatchesForJobJobsJobIDBatchesGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (o *ListJobBatchesForJobJobsJobIDBatchesGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListJobBatchesForJobJobsJobIDBatchesGetResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
