// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type ListMyBatchesBatchesMineGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseListMyBatchesBatchesMineGet []components.BatchRead
}

func (o *ListMyBatchesBatchesMineGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListMyBatchesBatchesMineGetResponse) GetResponseListMyBatchesBatchesMineGet() []components.BatchRead {
	if o == nil {
		return nil
	}
	return o.ResponseListMyBatchesBatchesMineGet
}
