// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type ListValidationsValidationsGetRequest struct {
	CurrentUserPayload any    `queryParam:"style=form,explode=true,name=current_user_payload"`
	Skip               *int64 `default:"0" queryParam:"style=form,explode=true,name=skip"`
	Limit              *int64 `default:"100" queryParam:"style=form,explode=true,name=limit"`
	// Field to sort by
	SortBy *string `queryParam:"style=form,explode=true,name=sort_by"`
	// Sort direction (asc or desc)
	SortOrder *string `default:"asc" queryParam:"style=form,explode=true,name=sort_order"`
	// Filter by test case ID
	TestCaseID *string `queryParam:"style=form,explode=true,name=test_case_id"`
	// Filter by validator user ID
	ValidatorID *string `queryParam:"style=form,explode=true,name=validator_id"`
	// Filter by acceptance status
	IsAccepted *bool `queryParam:"style=form,explode=true,name=is_accepted"`
	// Filter by creation date (ISO format)
	CreatedAfter *string `queryParam:"style=form,explode=true,name=created_after"`
	// Filter by creation date (ISO format)
	CreatedBefore *string `queryParam:"style=form,explode=true,name=created_before"`
}

func (l ListValidationsValidationsGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListValidationsValidationsGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListValidationsValidationsGetRequest) GetCurrentUserPayload() any {
	if o == nil {
		return nil
	}
	return o.CurrentUserPayload
}

func (o *ListValidationsValidationsGetRequest) GetSkip() *int64 {
	if o == nil {
		return nil
	}
	return o.Skip
}

func (o *ListValidationsValidationsGetRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListValidationsValidationsGetRequest) GetSortBy() *string {
	if o == nil {
		return nil
	}
	return o.SortBy
}

func (o *ListValidationsValidationsGetRequest) GetSortOrder() *string {
	if o == nil {
		return nil
	}
	return o.SortOrder
}

func (o *ListValidationsValidationsGetRequest) GetTestCaseID() *string {
	if o == nil {
		return nil
	}
	return o.TestCaseID
}

func (o *ListValidationsValidationsGetRequest) GetValidatorID() *string {
	if o == nil {
		return nil
	}
	return o.ValidatorID
}

func (o *ListValidationsValidationsGetRequest) GetIsAccepted() *bool {
	if o == nil {
		return nil
	}
	return o.IsAccepted
}

func (o *ListValidationsValidationsGetRequest) GetCreatedAfter() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAfter
}

func (o *ListValidationsValidationsGetRequest) GetCreatedBefore() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBefore
}

type ListValidationsValidationsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	PaginatedResponseTestCaseValidationRead *components.PaginatedResponseTestCaseValidationRead
}

func (o *ListValidationsValidationsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListValidationsValidationsGetResponse) GetPaginatedResponseTestCaseValidationRead() *components.PaginatedResponseTestCaseValidationRead {
	if o == nil {
		return nil
	}
	return o.PaginatedResponseTestCaseValidationRead
}
