// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type ListUserAPIKeysAPIKeysGetRequest struct {
	Limit  *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListUserAPIKeysAPIKeysGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListUserAPIKeysAPIKeysGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListUserAPIKeysAPIKeysGetRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListUserAPIKeysAPIKeysGetRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type ListUserAPIKeysAPIKeysGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ListAPIKeysResponse *components.ListAPIKeysResponse
}

func (o *ListUserAPIKeysAPIKeysGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListUserAPIKeysAPIKeysGetResponse) GetListAPIKeysResponse() *components.ListAPIKeysResponse {
	if o == nil {
		return nil
	}
	return o.ListAPIKeysResponse
}
