// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type ListStagesStagesGetRequest struct {
	Skip  *int64 `default:"0" queryParam:"style=form,explode=true,name=skip"`
	Limit *int64 `default:"100" queryParam:"style=form,explode=true,name=limit"`
}

func (l ListStagesStagesGetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListStagesStagesGetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListStagesStagesGetRequest) GetSkip() *int64 {
	if o == nil {
		return nil
	}
	return o.Skip
}

func (o *ListStagesStagesGetRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

type ListStagesStagesGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	StageListResponse *components.StageListResponse
}

func (o *ListStagesStagesGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListStagesStagesGetResponse) GetStageListResponse() *components.StageListResponse {
	if o == nil {
		return nil
	}
	return o.StageListResponse
}
