// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type PingStagesStagesPingGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponsePingStagesStagesPingGet map[string]string
}

func (o *PingStagesStagesPingGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PingStagesStagesPingGetResponse) GetResponsePingStagesStagesPingGet() map[string]string {
	if o == nil {
		return nil
	}
	return o.ResponsePingStagesStagesPingGet
}
