// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type PrefectWebhookIntegrationsPrefectWebhookPostRequest struct {
	QueueName             *string                          `queryParam:"style=form,explode=true,name=queue_name"`
	PrefectWebhookPayload components.PrefectWebhookPayload `request:"mediaType=application/json"`
}

func (o *PrefectWebhookIntegrationsPrefectWebhookPostRequest) GetQueueName() *string {
	if o == nil {
		return nil
	}
	return o.QueueName
}

func (o *PrefectWebhookIntegrationsPrefectWebhookPostRequest) GetPrefectWebhookPayload() components.PrefectWebhookPayload {
	if o == nil {
		return components.PrefectWebhookPayload{}
	}
	return o.PrefectWebhookPayload
}

type PrefectWebhookIntegrationsPrefectWebhookPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (o *PrefectWebhookIntegrationsPrefectWebhookPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PrefectWebhookIntegrationsPrefectWebhookPostResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
