// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type SDKLoginAuthSDKLoginPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	JWTToken *components.JWTToken
}

func (o *SDKLoginAuthSDKLoginPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SDKLoginAuthSDKLoginPostResponse) GetJWTToken() *components.JWTToken {
	if o == nil {
		return nil
	}
	return o.JWTToken
}
