// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type SubmitValidatorTaskValidatorTasksValidatorTaskIDSubmitPostRequest struct {
	ValidatorTaskID string `pathParam:"style=simple,explode=false,name=validator_task_id"`
}

func (o *SubmitValidatorTaskValidatorTasksValidatorTaskIDSubmitPostRequest) GetValidatorTaskID() string {
	if o == nil {
		return ""
	}
	return o.ValidatorTaskID
}

type SubmitValidatorTaskValidatorTasksValidatorTaskIDSubmitPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	Any any
}

func (o *SubmitValidatorTaskValidatorTasksValidatorTaskIDSubmitPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SubmitValidatorTaskValidatorTasksValidatorTaskIDSubmitPostResponse) GetAny() any {
	if o == nil {
		return nil
	}
	return o.Any
}
