// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type UpdateStageStagesStageIDPutRequest struct {
	StageID            int64                         `pathParam:"style=simple,explode=false,name=stage_id"`
	StageUpdatePayload components.StageUpdatePayload `request:"mediaType=application/json"`
}

func (o *UpdateStageStagesStageIDPutRequest) GetStageID() int64 {
	if o == nil {
		return 0
	}
	return o.StageID
}

func (o *UpdateStageStagesStageIDPutRequest) GetStageUpdatePayload() components.StageUpdatePayload {
	if o == nil {
		return components.StageUpdatePayload{}
	}
	return o.StageUpdatePayload
}

type UpdateStageStagesStageIDPutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	StageDetailsResponse *components.StageDetailsResponse
}

func (o *UpdateStageStagesStageIDPutResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateStageStagesStageIDPutResponse) GetStageDetailsResponse() *components.StageDetailsResponse {
	if o == nil {
		return nil
	}
	return o.StageDetailsResponse
}
