// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type UpdateUserMeUsersMePatchRequest struct {
	Args       any                   `queryParam:"style=form,explode=true,name=args"`
	Kwargs     any                   `queryParam:"style=form,explode=true,name=kwargs"`
	UserUpdate components.UserUpdate `request:"mediaType=application/json"`
}

func (o *UpdateUserMeUsersMePatchRequest) GetArgs() any {
	if o == nil {
		return nil
	}
	return o.Args
}

func (o *UpdateUserMeUsersMePatchRequest) GetKwargs() any {
	if o == nil {
		return nil
	}
	return o.Kwargs
}

func (o *UpdateUserMeUsersMePatchRequest) GetUserUpdate() components.UserUpdate {
	if o == nil {
		return components.UserUpdate{}
	}
	return o.UserUpdate
}

type UpdateUserMeUsersMePatchResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	UserRead *components.UserRead
}

func (o *UpdateUserMeUsersMePatchResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateUserMeUsersMePatchResponse) GetUserRead() *components.UserRead {
	if o == nil {
		return nil
	}
	return o.UserRead
}
