// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type UpdateTestCaseTestCasesTestCaseIDPutRequest struct {
	TestCaseID                               string                                              `pathParam:"style=simple,explode=false,name=test_case_id"`
	BodyUpdateTestCaseTestCasesTestCaseIDPut components.BodyUpdateTestCaseTestCasesTestCaseIDPut `request:"mediaType=application/json"`
}

func (o *UpdateTestCaseTestCasesTestCaseIDPutRequest) GetTestCaseID() string {
	if o == nil {
		return ""
	}
	return o.TestCaseID
}

func (o *UpdateTestCaseTestCasesTestCaseIDPutRequest) GetBodyUpdateTestCaseTestCasesTestCaseIDPut() components.BodyUpdateTestCaseTestCasesTestCaseIDPut {
	if o == nil {
		return components.BodyUpdateTestCaseTestCasesTestCaseIDPut{}
	}
	return o.BodyUpdateTestCaseTestCasesTestCaseIDPut
}

type UpdateTestCaseTestCasesTestCaseIDPutResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	TestCaseRead *components.TestCaseRead
}

func (o *UpdateTestCaseTestCasesTestCaseIDPutResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateTestCaseTestCasesTestCaseIDPutResponse) GetTestCaseRead() *components.TestCaseRead {
	if o == nil {
		return nil
	}
	return o.TestCaseRead
}
