// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flowaicom/flowai-sdk-go/models/components"
)

type VerifyValidatorAccessAuthValidatorsVerifyAccessPostResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Response
	ResponseVerifyValidatorAccessAuthValidatorsVerifyAccessPost map[string]string
}

func (o *VerifyValidatorAccessAuthValidatorsVerifyAccessPostResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VerifyValidatorAccessAuthValidatorsVerifyAccessPostResponse) GetResponseVerifyValidatorAccessAuthValidatorsVerifyAccessPost() map[string]string {
	if o == nil {
		return nil
	}
	return o.ResponseVerifyValidatorAccessAuthValidatorsVerifyAccessPost
}
