// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type APIKeyUpdate struct {
	// Optional user-friendly name for the key
	KeyName  *string `json:"key_name,omitempty"`
	IsActive *bool   `json:"is_active,omitempty"`
}

func (o *APIKeyUpdate) GetKeyName() *string {
	if o == nil {
		return nil
	}
	return o.KeyName
}

func (o *APIKeyUpdate) GetIsActive() *bool {
	if o == nil {
		return nil
	}
	return o.IsActive
}
