// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

// BatchStatusRead - Schema for returning batch status, primarily derived from its PipelineRun.
type BatchStatusRead struct {
	BatchID              string    `json:"batch_id"`
	PipelineRunID        string    `json:"pipeline_run_id"`
	Status               string    `json:"status"`
	ExternalRunID        *string   `json:"external_run_id,omitempty"`
	PipelineRunUpdatedAt time.Time `json:"pipeline_run_updated_at"`
}

func (b BatchStatusRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchStatusRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BatchStatusRead) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

func (o *BatchStatusRead) GetPipelineRunID() string {
	if o == nil {
		return ""
	}
	return o.PipelineRunID
}

func (o *BatchStatusRead) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *BatchStatusRead) GetExternalRunID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalRunID
}

func (o *BatchStatusRead) GetPipelineRunUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.PipelineRunUpdatedAt
}
