// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BodyUpdateTestCaseTestCasesTestCaseIDPut struct {
	// Schema for updating a test case (all fields optional)
	TestCaseIn TestCaseUpdate `json:"test_case_in"`
	// Schema representing the essential parts of a JWT payload for user identification.
	CurrentUserPayload JWTPayload `json:"current_user_payload"`
}

func (o *BodyUpdateTestCaseTestCasesTestCaseIDPut) GetTestCaseIn() TestCaseUpdate {
	if o == nil {
		return TestCaseUpdate{}
	}
	return o.TestCaseIn
}

func (o *BodyUpdateTestCaseTestCasesTestCaseIDPut) GetCurrentUserPayload() JWTPayload {
	if o == nil {
		return JWTPayload{}
	}
	return o.CurrentUserPayload
}
