// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

type DatasetRead struct {
	Name          string    `json:"name"`
	Description   *string   `json:"description,omitempty"`
	JobID         string    `json:"job_id"`
	PipelineRunID string    `json:"pipeline_run_id"`
	ID            string    `json:"id"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (d DatasetRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DatasetRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DatasetRead) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DatasetRead) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *DatasetRead) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

func (o *DatasetRead) GetPipelineRunID() string {
	if o == nil {
		return ""
	}
	return o.PipelineRunID
}

func (o *DatasetRead) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DatasetRead) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *DatasetRead) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
