// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DatasetGenerationRequest struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

func (o *DatasetGenerationRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *DatasetGenerationRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
