// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

type DatasetItemRead struct {
	DatasetID string         `json:"dataset_id"`
	ItemData  map[string]any `json:"item_data"`
	ID        string         `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (d DatasetItemRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DatasetItemRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *DatasetItemRead) GetDatasetID() string {
	if o == nil {
		return ""
	}
	return o.DatasetID
}

func (o *DatasetItemRead) GetItemData() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.ItemData
}

func (o *DatasetItemRead) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DatasetItemRead) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *DatasetItemRead) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
