// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DatasetItemListResponse struct {
	Items      []DatasetItemRead `json:"items"`
	Pagination PaginationDetails `json:"pagination"`
}

func (o *DatasetItemListResponse) GetItems() []DatasetItemRead {
	if o == nil {
		return []DatasetItemRead{}
	}
	return o.Items
}

func (o *DatasetItemListResponse) GetPagination() PaginationDetails {
	if o == nil {
		return PaginationDetails{}
	}
	return o.Pagination
}
