// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FileUpload - Schema for file upload via base64 encoding
type FileUpload struct {
	Filename string `json:"filename"`
	// Base64 encoded file content
	Content string `json:"content"`
	// MIME type of the file
	ContentType *string `json:"content_type,omitempty"`
}

func (o *FileUpload) GetFilename() string {
	if o == nil {
		return ""
	}
	return o.Filename
}

func (o *FileUpload) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

func (o *FileUpload) GetContentType() *string {
	if o == nil {
		return nil
	}
	return o.ContentType
}
