// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

// GetValidationTaskForBatchResponseSchema - Response schema for getting a validation task for a batch.
type GetValidationTaskForBatchResponseSchema struct {
	ID         string                      `json:"id"`
	BatchID    string                      `json:"batch_id"`
	Status     string                      `json:"status"`
	CreatedAt  time.Time                   `json:"created_at"`
	UpdatedAt  time.Time                   `json:"updated_at"`
	Validators []ValidatorTaskDetailSchema `json:"validators"`
}

func (g GetValidationTaskForBatchResponseSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetValidationTaskForBatchResponseSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetValidationTaskForBatchResponseSchema) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetValidationTaskForBatchResponseSchema) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

func (o *GetValidationTaskForBatchResponseSchema) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *GetValidationTaskForBatchResponseSchema) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *GetValidationTaskForBatchResponseSchema) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *GetValidationTaskForBatchResponseSchema) GetValidators() []ValidatorTaskDetailSchema {
	if o == nil {
		return []ValidatorTaskDetailSchema{}
	}
	return o.Validators
}
