// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobBatchGenerationResponse struct {
	JobID        string `json:"jobId"`
	Message      string `json:"message"`
	FlowRunID    string `json:"flow_run_id"`
	FlowRunName  string `json:"flow_run_name"`
	FlowRunState string `json:"flow_run_state"`
}

func (o *JobBatchGenerationResponse) GetJobID() string {
	if o == nil {
		return ""
	}
	return o.JobID
}

func (o *JobBatchGenerationResponse) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *JobBatchGenerationResponse) GetFlowRunID() string {
	if o == nil {
		return ""
	}
	return o.FlowRunID
}

func (o *JobBatchGenerationResponse) GetFlowRunName() string {
	if o == nil {
		return ""
	}
	return o.FlowRunName
}

func (o *JobBatchGenerationResponse) GetFlowRunState() string {
	if o == nil {
		return ""
	}
	return o.FlowRunState
}
