// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobCreate struct {
	Config map[string]any `json:"config"`
}

func (o *JobCreate) GetConfig() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Config
}
