// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JobListResponse struct {
	Jobs       []JobResponse     `json:"jobs"`
	Pagination PaginationDetails `json:"pagination"`
}

func (o *JobListResponse) GetJobs() []JobResponse {
	if o == nil {
		return []JobResponse{}
	}
	return o.Jobs
}

func (o *JobListResponse) GetPagination() PaginationDetails {
	if o == nil {
		return PaginationDetails{}
	}
	return o.Pagination
}
