// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JWTPayload - Schema representing the essential parts of a JWT payload for user identification.
type JWTPayload struct {
	Sub string `json:"sub"`
}

func (o *JWTPayload) GetSub() string {
	if o == nil {
		return ""
	}
	return o.Sub
}
