// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type JWTToken struct {
	Jwt string `json:"jwt"`
}

func (o *JWTToken) GetJwt() string {
	if o == nil {
		return ""
	}
	return o.Jwt
}
