// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

type ListAPIKeyItem struct {
	ID         string     `json:"id"`
	KeyName    string     `json:"keyName"`
	CreatedAt  time.Time  `json:"createdAt"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
}

func (l ListAPIKeyItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAPIKeyItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListAPIKeyItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListAPIKeyItem) GetKeyName() string {
	if o == nil {
		return ""
	}
	return o.KeyName
}

func (o *ListAPIKeyItem) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ListAPIKeyItem) GetLastUsedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastUsedAt
}
