// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

type Message struct {
	Role             string    `json:"role"`
	Content          *string   `json:"content,omitempty"`
	ID               string    `json:"id"`
	TrajectoryItemID *string   `json:"trajectory_item_id,omitempty"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (m Message) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Message) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Message) GetRole() string {
	if o == nil {
		return ""
	}
	return o.Role
}

func (o *Message) GetContent() *string {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *Message) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Message) GetTrajectoryItemID() *string {
	if o == nil {
		return nil
	}
	return o.TrajectoryItemID
}

func (o *Message) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *Message) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
