// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"github.com/flowaicom/flowai-sdk-go/types"
)

// MessageStepCreate - Schema for creating a message step.
type MessageStepCreate struct {
	Order   int64   `json:"order"`
	type_   *string `const:"message" json:"type"`
	Role    string  `json:"role"`
	Content string  `json:"content"`
}

func (m MessageStepCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessageStepCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *MessageStepCreate) GetOrder() int64 {
	if o == nil {
		return 0
	}
	return o.Order
}

func (o *MessageStepCreate) GetType() *string {
	return types.String("message")
}

func (o *MessageStepCreate) GetRole() string {
	if o == nil {
		return ""
	}
	return o.Role
}

func (o *MessageStepCreate) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}
