// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginatedResponseTestCaseValidationRead struct {
	Items   []TestCaseValidationRead `json:"items"`
	Total   int64                    `json:"total"`
	Page    int64                    `json:"page"`
	Pages   int64                    `json:"pages"`
	HasMore bool                     `json:"has_more"`
}

func (o *PaginatedResponseTestCaseValidationRead) GetItems() []TestCaseValidationRead {
	if o == nil {
		return []TestCaseValidationRead{}
	}
	return o.Items
}

func (o *PaginatedResponseTestCaseValidationRead) GetTotal() int64 {
	if o == nil {
		return 0
	}
	return o.Total
}

func (o *PaginatedResponseTestCaseValidationRead) GetPage() int64 {
	if o == nil {
		return 0
	}
	return o.Page
}

func (o *PaginatedResponseTestCaseValidationRead) GetPages() int64 {
	if o == nil {
		return 0
	}
	return o.Pages
}

func (o *PaginatedResponseTestCaseValidationRead) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}
