// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginationInfo struct {
	TotalCount int64 `json:"totalCount"`
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
}

func (o *PaginationInfo) GetTotalCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalCount
}

func (o *PaginationInfo) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}

func (o *PaginationInfo) GetOffset() int64 {
	if o == nil {
		return 0
	}
	return o.Offset
}
