// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

type PrefectFlowRunInfo struct {
	PrefectFlowRunID   string     `json:"prefect_flow_run_id"`
	PrefectFlowRunName *string    `json:"prefect_flow_run_name,omitempty"`
	StateType          *string    `json:"state_type,omitempty"`
	StateMessage       *string    `json:"state_message,omitempty"`
	StateTimestamp     *time.Time `json:"state_timestamp,omitempty"`
}

func (p PrefectFlowRunInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PrefectFlowRunInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PrefectFlowRunInfo) GetPrefectFlowRunID() string {
	if o == nil {
		return ""
	}
	return o.PrefectFlowRunID
}

func (o *PrefectFlowRunInfo) GetPrefectFlowRunName() *string {
	if o == nil {
		return nil
	}
	return o.PrefectFlowRunName
}

func (o *PrefectFlowRunInfo) GetStateType() *string {
	if o == nil {
		return nil
	}
	return o.StateType
}

func (o *PrefectFlowRunInfo) GetStateMessage() *string {
	if o == nil {
		return nil
	}
	return o.StateMessage
}

func (o *PrefectFlowRunInfo) GetStateTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.StateTimestamp
}
