// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PrefectWebhookPayload struct {
	FlowRun PrefectFlowRunInfo `json:"flow_run"`
}

func (o *PrefectWebhookPayload) GetFlowRun() PrefectFlowRunInfo {
	if o == nil {
		return PrefectFlowRunInfo{}
	}
	return o.FlowRun
}
