// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProjectUpdate struct {
	// New name for the project.
	Name *string `json:"name,omitempty"`
	// New description for the project.
	Description *string `json:"description,omitempty"`
}

func (o *ProjectUpdate) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ProjectUpdate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
