// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProjectCreate struct {
	// Name of the project.
	Name string `json:"name"`
	// Description of the project.
	Description *string `json:"description,omitempty"`
}

func (o *ProjectCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ProjectCreate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
