// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProjectArchiveResponse struct {
	ID       string `json:"id"`
	IsActive bool   `json:"is_active"`
}

func (o *ProjectArchiveResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ProjectArchiveResponse) GetIsActive() bool {
	if o == nil {
		return false
	}
	return o.IsActive
}
