// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ProjectValidatorCreate - Schema for adding a validator to a project.
type ProjectValidatorCreate struct {
	// Email address of the user to add as a validator.
	Email string `json:"email"`
}

func (o *ProjectValidatorCreate) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}
