// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StageUpdatePayload struct {
	// New original filename for the stage.
	OriginalFilename *string `json:"original_filename,omitempty"`
}

func (o *StageUpdatePayload) GetOriginalFilename() *string {
	if o == nil {
		return nil
	}
	return o.OriginalFilename
}
