// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StageListResponse struct {
	Stages []StageDetailsResponse `json:"stages"`
	Total  int64                  `json:"total"`
	Skip   int64                  `json:"skip"`
	Limit  int64                  `json:"limit"`
}

func (o *StageListResponse) GetStages() []StageDetailsResponse {
	if o == nil {
		return []StageDetailsResponse{}
	}
	return o.Stages
}

func (o *StageListResponse) GetTotal() int64 {
	if o == nil {
		return 0
	}
	return o.Total
}

func (o *StageListResponse) GetSkip() int64 {
	if o == nil {
		return 0
	}
	return o.Skip
}

func (o *StageListResponse) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}
