// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StageDetailsResponse struct {
	ID               string  `json:"id"`
	ProjectID        string  `json:"project_id"`
	S3Path           string  `json:"s3_path"`
	OriginalFilename *string `json:"original_filename,omitempty"`
	SourceType       string  `json:"source_type"`
}

func (o *StageDetailsResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *StageDetailsResponse) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *StageDetailsResponse) GetS3Path() string {
	if o == nil {
		return ""
	}
	return o.S3Path
}

func (o *StageDetailsResponse) GetOriginalFilename() *string {
	if o == nil {
		return nil
	}
	return o.OriginalFilename
}

func (o *StageDetailsResponse) GetSourceType() string {
	if o == nil {
		return ""
	}
	return o.SourceType
}
