// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StageCreationRequest - Schema for creating stages via SDK (compatible with JSON)
type StageCreationRequest struct {
	Files []FileUpload `json:"files"`
	// Enum for stage file types that inherits from str for better JSON/OpenAPI compatibility
	SourceType StageFileTypeEnum `json:"source_type"`
	// UUID of the project
	ProjectID string `json:"project_id"`
}

func (o *StageCreationRequest) GetFiles() []FileUpload {
	if o == nil {
		return []FileUpload{}
	}
	return o.Files
}

func (o *StageCreationRequest) GetSourceType() StageFileTypeEnum {
	if o == nil {
		return StageFileTypeEnum("")
	}
	return o.SourceType
}

func (o *StageCreationRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}
