// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TestCaseValidationUpdate - Schema for updating a TestCaseValidation
type TestCaseValidationUpdate struct {
	IsAccepted    *bool                         `json:"is_accepted,omitempty"`
	Feedback      *string                       `json:"feedback,omitempty"`
	ItemFeedbacks []ValidationItemFeedbackInput `json:"item_feedbacks,omitempty"`
}

func (o *TestCaseValidationUpdate) GetIsAccepted() *bool {
	if o == nil {
		return nil
	}
	return o.IsAccepted
}

func (o *TestCaseValidationUpdate) GetFeedback() *string {
	if o == nil {
		return nil
	}
	return o.Feedback
}

func (o *TestCaseValidationUpdate) GetItemFeedbacks() []ValidationItemFeedbackInput {
	if o == nil {
		return nil
	}
	return o.ItemFeedbacks
}
