// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TestCaseUpdate - Schema for updating a test case (all fields optional)
type TestCaseUpdate struct {
	Name           *string `json:"name,omitempty"`
	Description    *string `json:"description,omitempty"`
	ExpectedOutput *string `json:"expected_output,omitempty"`
	Status         *string `json:"status,omitempty"`
	IsActive       *bool   `json:"is_active,omitempty"`
}

func (o *TestCaseUpdate) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TestCaseUpdate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *TestCaseUpdate) GetExpectedOutput() *string {
	if o == nil {
		return nil
	}
	return o.ExpectedOutput
}

func (o *TestCaseUpdate) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *TestCaseUpdate) GetIsActive() *bool {
	if o == nil {
		return nil
	}
	return o.IsActive
}
