// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

type ToolOutput struct {
	Output     map[string]any `json:"output"`
	ID         string         `json:"id"`
	ToolCallID string         `json:"tool_call_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

func (t ToolOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ToolOutput) GetOutput() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Output
}

func (o *ToolOutput) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ToolOutput) GetToolCallID() string {
	if o == nil {
		return ""
	}
	return o.ToolCallID
}

func (o *ToolOutput) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ToolOutput) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
