// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"github.com/flowaicom/flowai-sdk-go/types"
)

// ToolCallStepCreate - Schema for creating a tool call step.
type ToolCallStepCreate struct {
	Order     int64   `json:"order"`
	type_     *string `const:"tool_call" json:"type"`
	ToolName  string  `json:"tool_name"`
	Arguments any     `json:"arguments,omitempty"`
	Output    any     `json:"output,omitempty"`
}

func (t ToolCallStepCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolCallStepCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *ToolCallStepCreate) GetOrder() int64 {
	if o == nil {
		return 0
	}
	return o.Order
}

func (o *ToolCallStepCreate) GetType() *string {
	return types.String("tool_call")
}

func (o *ToolCallStepCreate) GetToolName() string {
	if o == nil {
		return ""
	}
	return o.ToolName
}

func (o *ToolCallStepCreate) GetArguments() any {
	if o == nil {
		return nil
	}
	return o.Arguments
}

func (o *ToolCallStepCreate) GetOutput() any {
	if o == nil {
		return nil
	}
	return o.Output
}
