// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

type ToolCall struct {
	ToolName         string         `json:"tool_name"`
	Arguments        map[string]any `json:"arguments"`
	ID               string         `json:"id"`
	TrajectoryItemID *string        `json:"trajectory_item_id,omitempty"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ToolOutput       *ToolOutput    `json:"tool_output,omitempty"`
}

func (t ToolCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ToolCall) GetToolName() string {
	if o == nil {
		return ""
	}
	return o.ToolName
}

func (o *ToolCall) GetArguments() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Arguments
}

func (o *ToolCall) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ToolCall) GetTrajectoryItemID() *string {
	if o == nil {
		return nil
	}
	return o.TrajectoryItemID
}

func (o *ToolCall) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ToolCall) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *ToolCall) GetToolOutput() *ToolOutput {
	if o == nil {
		return nil
	}
	return o.ToolOutput
}
