// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ValidatorVerifyAccessRequest struct {
	ValidationTaskID string `json:"validationTaskId"`
	ValidatorID      string `json:"validatorId"`
	UniqueURLKey     string `json:"uniqueUrlKey"`
}

func (o *ValidatorVerifyAccessRequest) GetValidationTaskID() string {
	if o == nil {
		return ""
	}
	return o.ValidationTaskID
}

func (o *ValidatorVerifyAccessRequest) GetValidatorID() string {
	if o == nil {
		return ""
	}
	return o.ValidatorID
}

func (o *ValidatorVerifyAccessRequest) GetUniqueURLKey() string {
	if o == nil {
		return ""
	}
	return o.UniqueURLKey
}
