// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

// ValidationTaskRead - Schema for reading a validation task.
type ValidationTaskRead struct {
	BatchID   string    `json:"batch_id"`
	Status    string    `json:"status"`
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (v ValidationTaskRead) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ValidationTaskRead) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ValidationTaskRead) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

func (o *ValidationTaskRead) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *ValidationTaskRead) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ValidationTaskRead) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ValidationTaskRead) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
