// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flowaicom/flowai-sdk-go/internal/utils"
	"time"
)

// ValidationItemFeedback - Schema for reading/returning validation item feedback
type ValidationItemFeedback struct {
	TrajectoryItemID     string    `json:"trajectory_item_id"`
	FeedbackText         string    `json:"feedback_text"`
	ID                   string    `json:"id"`
	TestCaseValidationID string    `json:"test_case_validation_id"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

func (v ValidationItemFeedback) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ValidationItemFeedback) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ValidationItemFeedback) GetTrajectoryItemID() string {
	if o == nil {
		return ""
	}
	return o.TrajectoryItemID
}

func (o *ValidationItemFeedback) GetFeedbackText() string {
	if o == nil {
		return ""
	}
	return o.FeedbackText
}

func (o *ValidationItemFeedback) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ValidationItemFeedback) GetTestCaseValidationID() string {
	if o == nil {
		return ""
	}
	return o.TestCaseValidationID
}

func (o *ValidationItemFeedback) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ValidationItemFeedback) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
