// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ValidationItemFeedbackInput struct {
	ItemID   string  `json:"itemId"`
	Feedback *string `json:"feedback,omitempty"`
}

func (o *ValidationItemFeedbackInput) GetItemID() string {
	if o == nil {
		return ""
	}
	return o.ItemID
}

func (o *ValidationItemFeedbackInput) GetFeedback() *string {
	if o == nil {
		return nil
	}
	return o.Feedback
}
